# Generated by Django 4.2.28 on 2026-03-03 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='education.grade')),
            ],
            options={
                'ordering': ['grade__number', 'name'],
                'unique_together': {('grade', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField(blank=True, help_text='YouTube embed URL: https://www.youtube.com/embed/VIDEO_ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='topic_pdfs/')),
                ('text', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='education.subject')),
            ],
            options={
                'ordering': ['subject__grade__number', 'subject__name', 'order', 'title'],
            },
        ),
    ]
