# Generated by Django 4.2.28 on 2026-03-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='video_url',
        ),
        migrations.AddField(
            model_name='topic',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/topics/'),
        ),
    ]
