# Generated by Django 4.2.28 on 2026-03-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselesson',
            old_name='video_url',
            new_name='video_embed_url',
        ),
        migrations.AddField(
            model_name='courselesson',
            name='video_watch_url',
            field=models.URLField(blank=True),
        ),
    ]
