# Generated by Django 4.2.28 on 2026-03-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_video_url_courselesson_video_embed_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselesson',
            name='video_embed_url',
        ),
        migrations.RemoveField(
            model_name='courselesson',
            name='video_watch_url',
        ),
        migrations.AddField(
            model_name='courselesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/courses/'),
        ),
    ]
