# Generated by Django 4.2.28 on 2026-03-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lessontopic',
            name='subject',
        ),
        migrations.DeleteModel(
            name='ParentTraining',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
        migrations.DeleteModel(
            name='VideoLesson',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
        migrations.DeleteModel(
            name='LessonTopic',
        ),
        migrations.DeleteModel(
            name='SchoolGrade',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
